title: Zhong Lei's Homepage
page-top-title: Zhong Lei
#top-section-bg-text: Be what you wanna be
home-subtitle: Zhong Lei&ensp;|&ensp;钟磊
copyright-text: '&copy; Zhong Lei 2023-2026. All Rights Reserved.'
